mvn install:install-file  -Dfile=cordova-1.8.1.jar \
                          -DgroupId=org.apache.cordova \
                          -DartifactId=cordova \
                          -Dversion=1.8.1 \
                          -Dsources=cordova-1.8.1-sources.jar \
                          -Dpackaging=jar
mvn install:install-file  -Dfile=phonegapproxy-1.0.html5.zip \
                          -DgroupId=com.opitzconsulting.phonegapproxy \
                          -DartifactId=phonegapproxy \
                          -Dversion=1.0 \
                          -Dpackaging=zip \
                          -Dclassifier=html5